// lib/features/flashcards/data/models/quiz_model.dart
//
// StudySpark — Isar collections for AI-generated and manual quizzes.
//
// Three related collections:
//   QuizQuestionModel — a single question with options + answer
//   QuizAttemptModel  — one attempt at a quiz (score, answers chosen)
//   QuizModel         — the quiz itself (metadata + question list)
//
// AI quizzes are generated by HuggingFace deepset/roberta-base-squad2
// from a linked [NoteModel] and cached here to avoid re-generation.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:isar/isar.dart';

import '../../../../core/enums/app_enums.dart';

part 'quiz_model.g.dart';

// ─── QuizOptionModel (embedded) ──────────────────────────────────────────────

/// One answer option for a [QuizQuestionModel].
@embedded
class QuizOptionModel {
  QuizOptionModel({
    this.id = '',
    this.text = '',
    this.isCorrect = false,
    this.explanation = '',
  });

  /// Single-char identifier: "A", "B", "C", "D".
  String id;
  String text;
  bool isCorrect;

  /// Shown after reveal to explain why this option is right/wrong.
  String explanation;
}

// ─── QuizQuestionModel ────────────────────────────────────────────────────────

/// A single question belonging to a [QuizModel].
@Collection()
class QuizQuestionModel {
  QuizQuestionModel({
    this.id = Isar.autoIncrement,
    this.uuid = '',
    this.quizId = '',
    this.subjectId = '',
    this.questionType = QuizQuestionType.multipleChoice,
    this.questionText = '',
    this.options = const [],
    this.correctAnswer = '',
    this.explanation = '',
    this.difficultyScore = 1,
    this.sourceNoteId = '',
    this.position = 0,
    this.imagePathQuestion = '',
    this.timeLimitSeconds = 0,
    this.tags = const [],
    this.createdAt,
  });

  Id id;

  @Index(unique: true, replace: true)
  String uuid;

  @Index()
  String quizId;

  @Index()
  String subjectId;

  @enumerated
  QuizQuestionType questionType;

  @Index(type: IndexType.words)
  String questionText;

  /// For multipleChoice / trueFalse; empty for shortAnswer.
  List<QuizOptionModel> options;

  /// Ground-truth answer text (option id for MC, "True"/"False" for T/F,
  /// or the expected string for shortAnswer).
  String correctAnswer;

  /// Full explanation of the correct answer (shown post-attempt).
  String explanation;

  /// Rough difficulty (1 = easy, 2 = medium, 3 = hard).
  int difficultyScore;

  /// UUID of the [NoteModel] this question was generated from; empty = manual.
  @Index()
  String sourceNoteId;

  /// Display order within the quiz.
  int position;

  /// Optional image file path shown with the question.
  String imagePathQuestion;

  /// Per-question time limit in seconds; 0 = use quiz-level default.
  int timeLimitSeconds;

  List<String> tags;

  @Index()
  DateTime? createdAt;
}

// ─── QuizAttemptAnswerModel (embedded) ───────────────────────────────────────

/// The user's answer to a single question in a [QuizAttemptModel].
@embedded
class QuizAttemptAnswerModel {
  QuizAttemptAnswerModel({
    this.questionUuid = '',
    this.chosenOptionId = '',
    this.chosenText = '',
    this.isCorrect = false,
    this.timeTakenSeconds = 0,
  });

  String questionUuid;
  String chosenOptionId;
  String chosenText;
  bool isCorrect;
  int timeTakenSeconds;
}

// ─── QuizAttemptModel ─────────────────────────────────────────────────────────

/// One scored run through a [QuizModel].
@Collection()
class QuizAttemptModel {
  QuizAttemptModel({
    this.id = Isar.autoIncrement,
    this.uuid = '',
    this.quizId = '',
    this.answers = const [],
    this.score = 0,
    this.totalQuestions = 0,
    this.durationSeconds = 0,
    this.startedAt,
    this.completedAt,
  });

  Id id;

  @Index(unique: true, replace: true)
  String uuid;

  @Index()
  String quizId;

  List<QuizAttemptAnswerModel> answers;

  /// Number of correct answers.
  int score;

  int totalQuestions;

  double get scorePercent =>
      totalQuestions == 0 ? 0.0 : score / totalQuestions;

  int durationSeconds;

  @Index()
  DateTime? startedAt;

  @Index()
  DateTime? completedAt;

  bool get isPassed => scorePercent >= 0.6; // 60% pass mark
}

// ─── QuizModel ────────────────────────────────────────────────────────────────

@Collection()
class QuizModel {
  QuizModel({
    this.id = Isar.autoIncrement,
    this.uuid = '',
    this.title = '',
    this.description = '',
    this.subjectId = '',
    this.sourceNoteId = '',
    this.tags = const [],
    this.questionCount = 0,
    this.defaultTimeLimitSeconds = 30,
    this.isAiGenerated = false,
    this.isPublished = false,
    this.bestScore = 0,
    this.attemptCount = 0,
    this.lastAttemptAt,
    this.createdAt,
    this.updatedAt,
  });

  Id id;

  @Index(unique: true, replace: true)
  String uuid;

  @Index(type: IndexType.value)
  String title;

  String description;

  @Index()
  String subjectId;

  /// UUID of the [NoteModel] this quiz was generated from; empty = manual.
  @Index()
  String sourceNoteId;

  List<String> tags;

  /// Cached count of [QuizQuestionModel] documents with [quizId] == [uuid].
  int questionCount;

  /// Default per-question time limit; individual questions may override.
  int defaultTimeLimitSeconds;

  /// True if generated via HuggingFace API.
  bool isAiGenerated;

  /// Drafts are only visible to the creator; published quizzes appear in search.
  @Index()
  bool isPublished;

  // ── Cached attempt stats (updated by repository) ──────────────────────────
  int bestScore; // best score% * 100 (0–100)
  int attemptCount;

  DateTime? lastAttemptAt;

  @Index()
  DateTime? createdAt;

  DateTime? updatedAt;
}
