// lib/features/tasks/data/models/task_model.dart
//
// Isar schema for a Task.
// Run: flutter pub run build_runner build --delete-conflicting-outputs

import 'package:isar/isar.dart';

part 'task_model.g.dart';  // generated by isar_generator

// ─── Enums ────────────────────────────────────────────────────────────────────

/// Priority level for sorting and visual styling.
enum TaskPriority { low, medium, high, urgent }

/// Lifecycle state of a task.
enum TaskStatus { todo, inProgress, completed, archived }

// ─── Schema ───────────────────────────────────────────────────────────────────
@collection
class TaskModel {
  Id id = Isar.autoIncrement;

  /// Client-generated UUID for deep-linking and notification IDs.
  @Index(unique: true)
  late String uuid;

  /// Task title — indexed for full-text search.
  @Index(type: IndexType.value)
  late String title;

  String? description;

  /// Associated subject (e.g. "Mathematics", "Physics")
  @Index()
  String? subject;

  /// Hex color string for the subject tag (e.g. "#6C4FF8")
  String? subjectColor;

  @enumerated
  TaskPriority priority = TaskPriority.medium;

  @enumerated
  TaskStatus status = TaskStatus.todo;

  /// Deadline (nullable for tasks without a due date)
  DateTime? dueDate;

  /// Reminder datetime (drives local notification scheduling)
  DateTime? reminderAt;

  DateTime createdAt = DateTime.now();
  DateTime updatedAt = DateTime.now();

  /// Estimated time in minutes (for scheduling)
  int? estimatedMinutes;

  /// Actual time spent in minutes (from focus sessions)
  int completedMinutes = 0;

  /// Sub-task titles stored as a simple list
  List<String> subtasks = [];

  /// Completed sub-task indices
  List<int> completedSubtaskIndices = [];

  /// Tags for filtering
  List<String> tags = [];

  bool isStarred = false;

  // ── Derived helpers (not persisted) ────────────────────────────────────────

  /// Progress 0.0–1.0 based on subtask completion.
  double get subtaskProgress {
    if (subtasks.isEmpty) return status == TaskStatus.completed ? 1.0 : 0.0;
    return completedSubtaskIndices.length / subtasks.length;
  }

  bool get isOverdue =>
      dueDate != null &&
      dueDate!.isBefore(DateTime.now()) &&
      status != TaskStatus.completed;
}

// ─── Note Model Stub ──────────────────────────────────────────────────────────
// (lives here temporarily; move to notes feature in production)
